blog/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import settings
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('muhammad.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

muhammad/urls.py
from django.urls import path
from muhammad.views import HomeView, about_page, AddPost, ArticleDetailView, DeletePostView, user_post, login_page, logout_page, register_page, UpdatePostView

app_name = 'muhammad'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', about_page, name='about'),
    path('post_form/', AddPost.as_view(), name='post_form'),
    # path('post_detail/', post_detail, name='post_detail'),
    path('post_conf_delete/', DeletePostView.as_view(), name='post_conf_delete'),
    path('user_post/', user_post, name='user_post'),
    path('login_page/', login_page, name='login_page'),
    path('logout_page/', logout_page, name='logout_page'),
    path('register/', register_page, name='register_page'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='post_detail'),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='update_epost'),
    path('article/<int:pk>/delete', DeletePostView.as_view(), name='delete_epost')
]

muhammad/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class UserProfile(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.username


class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.title + ' / ' + str(self.author)

    def get_absolute_url(self):
        return reverse('muhammad:home')

muhammad/forms.py
from django import forms
from .models import UserProfile, Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'author']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
        }


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['username', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }



class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

muhammad/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from muhammad.forms import RegistrationForm, LoginForm

from django.contrib.auth import authenticate, login
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from muhammad.models import Post
from .forms import PostForm


class HomeView(ListView):
    model = Post
    template_name = 'home.html'

class ArticleDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'

class AddPost(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'post_form.html'
    # fields = "__all__"


class UpdatePostView(UpdateView):
    model = Post
    # form_class = PostForm
    template_name = 'update_post.html'
    fields = ['title', 'body']
    success_url = reverse_lazy('muhammad:home')

class DeletePostView(DeleteView):
    model = Post
    template_name = 'post_confirm_delete.html'
    success_url = reverse_lazy('muhammad:home')


def about_page(request):
    return render(request, 'about.html')



def user_post(requset):
    return render(requset, 'user_posts.html')



def logout_page(request):
    return render(request, 'logout.html')



def register_page(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('muhammad:login_page')
    else:
        form = RegistrationForm()

    return render(request, 'register.html', {'form': form})





def login_page(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('muhammad:home')
            else:

                pass
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})

templates/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'muhammad:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'muhammad:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'muhammad:about' %}">About</a>
            </div>
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'muhammad:post_form' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:user_post' %}">Profile</a>
                <a class="nav-item nav-link" href="#">Logout</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:login_page' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:register_page' %}">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
                <h1>About Page</h1>
                    <div class="container mt-5">
                        <h2>About Us</h2>
                        <p>Welcome to our Django Blog! This blog is dedicated to sharing knowledge, experiences, and thoughts on various topics.</p>

                        <h3>Our Mission</h3>
                        <p>Our mission is to provide valuable and insightful content to our readers. We aim to engage, educate, and entertain through our blog posts.</p>

                        <h3>Meet the Team</h3>
                        <p>We are a passionate team of writers, developers, and enthusiasts who love sharing our expertise with the world.</p>

                        <!-- Add more content about your team, mission, etc. -->

                        <p>Feel free to explore our blog and discover a wide range of articles covering different subjects.</p>
                    </div>

                </div>
                <div class="col-md-4">
                  <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                      <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                      </ul>
                    </p>
                  </div>
                </div>
              </div>
            </main>

            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        </body>
        </html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'muhammad:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'muhammad:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'muhammad:post_form' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:user_post' %}">Profile</a>
                <a class="nav-item nav-link" href="#">Logout</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:login_page' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:register_page' %}">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h6>Django messages might be shown here</h3>
              </div>

            {% for post in object_list %}
              <article class="media content-section">
                <img class="rounded-circle article-img" src="{% static 'imgs/corey.jpeg' %}">
                <div class="media-body">
                  <div class="article-metadata">
                    <a class="mr-2" href="{% url 'muhammad:user_post' %}">{{ post.author }}</a>
                    <small class="text-muted">Feb 19, 2023</small>
                  </div>
                  <h5><a class="article-title" href="{% url 'muhammad:post_detail' post.pk %}">{{ post.title }}</a></h2>
                </div>
              </article>

            {% endfor %}


        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>User Login</title>
</head>
<body>
    <h2>User Login</h2>
    <form method="post" action="{% url 'muhammad:login_page' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/post_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'muhammad:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'muhammad:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'muhammad:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'muhammad:post_form' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:user_post' %}">Profile</a>
                <a class="nav-item nav-link" href="#">Logout</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:login_page' %}">Login</a>
                <a class="nav-item nav-link" href="{%  url 'muhammad:register_page' %}">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h6>Django messages might be shown here</h3>
              </div>
                <div class="content-section">
                    <form method="POST">
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Delete Post</legend>
                            <h2>Are you sure you want to delete the post "I have been watching a decade."</h2>
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                            <a class="btn btn-outline-secondary" href="{% url 'muhammad:post_detail' object.id %}">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-4">
              <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                  <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                  </ul>
                </p>
              </div>
            </div>
            </div>
            </main>

            <!-- Optional JavaScript -->
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
            </body>
            </html>

templates/post_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'muhammad:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'muhammad:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'muhammad:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'muhammad:post_form' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:user_post' %}">Profile</a>
                <a class="nav-item nav-link" href="#">Logout</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:login_page' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:register_page' %}">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h6>Django messages might be shown here</h3>
              </div>
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{% static 'imgs/corey.jpeg' %}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'muhammad:user_post' %}">RapidFork Technology</a>
        <small class="text-muted">Feb 19, 2023</small>
         <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="#">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'muhammad:post_conf_delete' %}">Delete</a>
          </div>

      </div>
      <h2 class="article-title">I have been watching a decade.</h2>
      <p class="article-content">I have been watching a decade worth of The Ask Project
        by Corey Gil-Shuster on YouTube. Makes me have very little hope of there ever
        being a two state solution. The Palestinians seem
        Makes me have very little hope of there ever
        being a two state solution. The Palestinians seem
      </p>
    </div>
  </article>
</div>
<div class="col-md-4">
  <div class="content-section">
    <h3>Our Sidebar</h3>
    <p class='text-muted'>You can put any information here you'd like.
      <ul class="list-group">
        <li class="list-group-item list-group-item-light">Latest Posts</li>
        <li class="list-group-item list-group-item-light">Announcements</li>
        <li class="list-group-item list-group-item-light">Calendars</li>
        <li class="list-group-item list-group-item-light">etc</li>
      </ul>
    </p>
  </div>
</div>
</div>
</main>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>User Registration</title>
</head>
<body>
    <h2>User Registration</h2>
    <form method="post" action="{% url 'muhammad:register_page' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>

templates/user_posts.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <title>Django Blog</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="#">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="#">Home</a>
              <a class="nav-item nav-link" href="{% url 'muhammad:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'muhammad:post_form' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:user_post' %}">Profile</a>
                <a class="nav-item nav-link" href="#">Logout</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:login_page' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'muhammad:register_page' %}">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h6>Django messages might be shown here</h3>
              </div>
            <h1 class="mb-3">Posts by Andrew Ng </h1>

            <article class="media content-section">
              <img class="rounded-circle article-img" src="{% static 'imgs/andrew.jpeg' %}">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'muhammad:user_post' %}">Andrew Ng</a>
                  <small class="text-muted">Aug 21, 2019</small>
                </div>
                <h4><a class="article-title" href="{% url 'muhammad:post_detail' %}">AI in Latin America: Announcing our first international office in Colombia</a></h2>
                <p class="article-content">I am excited to announce the opening of our office in Medellín, Colombia.
                  The office will serve as the Latin American headquarters for three of the companies in our AI ecosystem</p>
              </div>
            </article>
            <article class="media content-section">
              <img class="rounded-circle article-img" src="{% static 'imgs/andrew.jpeg' %}">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'muhammad:user_post' %}">Andrew Ng</a>
                  <small class="text-muted">Aug 21, 2019</small>
                </div>
                <h4><a class="article-title" href="{% url 'muhammad:post_detail' %}">Introducing the AI Transformation Playbook</a></h2>
                <p class="article-content">Dear friends,
                  I’m excited to share with you the AI Transformation Playbook. Drawn from my experience leading Google Brain,
                  Baidu’s AI Group, and Landing AI, this Playbook provides a roadmap for your company to transform into a great AI company.</p>
              </div>
            </article>


          </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Announcements</li>
              <li class="list-group-item list-group-item-light">Calendars</li>
              <li class="list-group-item list-group-item-light">etc</li>
            </ul>
          </p>
        </div>
      </div>
      </div>
      </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>